### ISSUE TITLE
pvrcnn result in pa-aug paper lower than original paper

### ISSUE THREAD

**Issue by turboxin** [sky77764/pa-aug.pytorch#1]
Hi @sky77764，thanks for sharing the code.

I have a question when reading the paper, moderate car val AP 3D@0.7 of pvrcnn is 84.84 in original pvrcnn paper and 83.61 in open-pcdet implementation, while in pa-aug paper is 80.43.
![pa-aug](https://user-images.githubusercontent.com/31332811/95649518-58ac4800-0b10-11eb-932d-9d3439fb9893.png)

Why is it much lower than original paper or open-pcdet  implementation.

**Comment by sky77764** [comment]
@turboxin Sorry for the confusing results.
We reported AP with 11 recall points but pvrcnn with 40.
The AP with 11 recall points is always lower than 40's.

**Comment by turboxin** [comment]
Hi @sky77764, thanks for the quick reply!

I noticed that pvrcnn also report 11 recall points result which is 83.90
![image](https://user-images.githubusercontent.com/31332811/95651375-91eab500-0b1c-11eb-9be1-c164c51ea165.png)

I'm wondering how do you get the 80.43 results since I couldn't find this in pvrcnn paper.

**Comment by turboxin** [comment]
Sorry the figure in last reply wasn't uploaded successfuly.

![pvrcnn](https://user-images.githubusercontent.com/31332811/95651447-09204900-0b1d-11eb-9ee2-cab7e29d4f4b.png)

**Comment by sky77764** [comment]
Ah, it's right. I missed it. 
![캡처](https://user-images.githubusercontent.com/12641262/95651615-92884900-0b26-11eb-9155-ae6ae474f25b.PNG)
These are the raw scores when I report results on the paper.
I only changed the batch size of the original OpenPCDet settings.
