### ISSUE TITLE
Does it support nuScenes dataset?

### ISSUE THREAD

**Issue by Biniang5510** [sky77764/pa-aug.pytorch#2]
Hi @sky77764 , may I know does it support nuScenes dataset. Can I use it on OpenPCDet pointpillar training? Thanks

**Comment by sky77764** [comment]
I've never tested nuScenes dataset, but I think this code cannot be used as it is.
The nuScenes and KITTI have different annotation format and different classes.
And it may cause some problems allocating partitions to objects.
To use the nuScenes dataset, you need to modify the init part of the PartAwareAugmentation class.

**Comment by Biniang5510** [comment]
Hi @sky77764 , is that mean the init part of the PartAwareAugmentation class is the only part that I have to modify if I am going to use nuScenes dataset? Sorry about that, I am new to this. May I know where this code should be placed in OpenPCDet?

**Comment by sky77764** [comment]
Yes. You need to change the number of partitions in __init__ and assign_box_points_partition function.

https://github.com/sky77764/OpenPCDet

I made a repo forked from OpenPCDet which contains a reference implementation of PA-AUG.
Follow the link above.
