### ISSUE TITLE
Implementation in OpenPCDet

### ISSUE THREAD

**Issue by AngYikHong** [sky77764/pa-aug.pytorch#3]
Hi @sky77764, thanks for your great works! May I know how can I implement this in OpenPCDet?

**Comment by sky77764** [comment]
https://github.com/sky77764/OpenPCDet

I made a repo forked from OpenPCDet which contains a reference implementation of PA-AUG.
Follow the link above.

**Comment by AngYikHong** [comment]
Hi @sky77764, do I have to rerun the data preparation again if I have run the original one in OpenPCDet?

**Comment by wangxin-fighting** [comment]
> https://github.com/sky77764/OpenPCDet
> 
> I made a repo forked from OpenPCDet which contains a reference implementation of PA-AUG.
Follow the link above.

   @sky77764 Hello, it's an honor for you to take the time to read the email I sent you. I recently read about your“ https://github.com/sky77764/OpenPCDet ”I found that the V0.3 version of the code written on this website does not support the spconv2 version. Could you please share the code that has been improved to support the spconv2 version? Looking forward to your reply, thank you. Wishing you a happy life!
